config/routes.rb
PostitTemplate::Application.routes.draw do
  root to: 'posts#index'
	
  get 'register', to: 'users#new'
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  get 'logout', to: 'sessions#destroy'

  resources :users, only: [:show, :create, :edit, :update]  
  resources :categories

  resources :posts, except: [:destroy] do 
    member do
      post :vote
    end
  	resources :comments, only: [:create] do 
      member do
        post :vote
      end
    end
  end
end

app/models/category.rb
class Category < ActiveRecord::Base
	has_many :post_categories
	has_many :posts, through: :post_categories

	validates :name, presence: true
end

app/models/comment.rb
class Comment < ActiveRecord::Base
	belongs_to :user
	belongs_to :post

	has_many :votes, as: :voteable 

	validates :body, presence: true
	def vote_total
		upvotes - downvotes
	end

	def upvotes
		self.votes.where(vote: true).size
	end

	def downvotes
		self.votes.where(vote: false).size
	end
end

app/models/post.rb
class Post < ActiveRecord::Base
	belongs_to :user
	has_many :comments
	has_many :post_categories
	has_many :categories, through: :post_categories
	has_many :votes, as: :voteable 

	validates :title, presence: true, length: {minimum: 5}
	validates :url, presence: true, uniqueness: true
	validates :description, presence: true

	def vote_total
		upvotes - downvotes
	end

	def upvotes
		self.votes.where(vote: true).size
	end

	def downvotes
		self.votes.where(vote: false).size
	end
end

app/models/post_category.rb
class PostCategory < ActiveRecord::Base
	belongs_to :post
	belongs_to :category
end

app/models/user.rb
class User < ActiveRecord::Base
	has_many :posts
	has_many :comments
	has_many :votes
	
	has_secure_password validation: false
 	validates :username, presence: true, length: {minimum: 5}
	validates :password, presence: true, on: :create, length: {minimum: 5}
 end

app/models/vote.rb
class Vote < ActiveRecord::Base
	belongs_to :user, class_name: 'User', foreign_key: 'user_id'
	belongs_to :comments, foreign_key: :id
	belongs_to :voteable, polymorphic: true

	validates_uniqueness_of :user, scope: [:voteable, :voteable_type]
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  helper_method :current_user, :logged_in?

  def current_user
  	current_user = User.find(session[:user_id]) if session[:user_id]

  end

  def logged_in?
  	!!current_user
  end

  def require_user 
  	if !logged_in?
  		flash[:error] = "Must be logged in to do that"
  		redirect_to root_path
  	end
  end
end

app/controllers/categories_controller.rb
#  categories GET    /categories(.:format)          categories#index
#               POST   /categories(.:format)          categories#create
#  new_category GET    /categories/new(.:format)      categories#new
# edit_category GET    /categories/:id/edit(.:format) categories#edit
#      category GET    /categories/:id(.:format)      categories#show
#               PATCH  /categories/:id(.:format)      categories#update
#               PUT    /categories/:id(.:format)      categories#update
#               DELETE /categories/:id(.:format)      categories#destroy


class CategoriesController < ApplicationController
	before_action :require_user, only: [:new, :create]
	def index
		@categories = Category.all
	end

	def show
		@categories = Category.find(params[:id])
	end

	def new
		@categories = Category.new
	end

	def create
		@categories = Category.new(categories_params)
		if @categories.save
			flash[:notice] = "Your category has been submited"
			redirect_to categories_path
		else
			render 'new'
		end
	end

	def edit
		
	end

	def update
	end

	private
	def categories_params
		params.require(:category).permit(:name)
	end
end

app/controllers/comments_controller.rb
# post_comments POST   /posts/:post_id/comments(.:format) comments#create
# vote_post POST   /posts/:id/vote(.:format)                   posts#vote
# vote_post_comment POST   /posts/:post_id/comments/:id/vote(.:format) comments#vote
class CommentsController < ApplicationController
	before_action :require_user

	def create
		@post = Post.find(params[:post_id])
		@comments = @post.comments.build(params.require(:comment).permit(:body))
		@comments.user = User.find(session[:user_id])

		if @comments.save  
			flash[:notice] = "Your comment was added"
			redirect_to post_path(@post)
		else
			render 'post/show'
		end

	end

	def vote
		
		comment = Comment.find(params[:id])
		vote = Vote.create(voteable: comment, user_id: current_user.id, vote: params[:vote])

		if vote.valid?
			flash[:notice] = "Your vote has been counted "
		else
			flash[:error] = "You can only vote once"
		end
		redirect_to :back
	end
end

app/controllers/posts_controller.rb
#Routes 
# post_comments POST   /posts/:post_id/comments(.:format)     comments#create
#  post_comment GET    /posts/:post_id/comments/:id(.:format) comments#show
#         posts GET    /posts(.:format)                       posts#index
#               POST   /posts(.:format)                       posts#create
#      new_post GET    /posts/new(.:format)                   posts#new
#     edit_post GET    /posts/:id/edit(.:format)              posts#edit
#          post GET    /posts/:id(.:format)                   posts#show
#               PATCH  /posts/:id(.:format)                   posts#update
#               PUT    /posts/:id(.:format)                   posts#update

class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :vote]
  before_action :require_user, except: [:show, :index]

  def index
  	@post = Post.all.sort_by{|x| x.vote_total}.reverse
  end

  def show
    @comments = Comment.new
  end

  def new
  	@post = Post.new
  end

  def create

  	@post = Post.new(post_params)
  	@post.user = User.find(session[:user_id]) # TODO: Change once we have authentication is created 

  	if  @post.save
  		flash[:notice] = "Your post was created."
  		redirect_to posts_path
  	else
  		render 'new'
  	end
  end

  def edit; end

  def update
    if @post.update(post_params)
      flash[:notice] = '"'+"#{@post.title}"+'"'+" was updated"
      redirect_to posts_path
    else 
      render :edit
    end 
  end 

  def vote
    @vote = Vote.create(voteable: @post, user_id: current_user.id, vote: params[:vote])

    if @vote.valid? 
      flash[:notice] = "Your vote has been counted"

    else
      flash[:error] = "You can only vote once"
    end
    redirect_to posts_path
  end

  private 

  def post_params
  	params.require(:post).permit(:title, :url, :description, category_ids: [])
  end

  def set_post
    @post = Post.find(params[:id])
  end


end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
	def new
		
	end

	def create
		user = User.find_by(username: params[:username])
		if user && user.authenticate(params[:password])
			session[:user_id] = user.id
			flash[:notice] = "Welcome back #{user.username}"
			redirect_to root_path
		else
			flash[:error] = "Something went wrong with your username or password"
			render :new
		end
	end

	def destroy
		session[:user_id] = nil
		flash[:notice] = "You have been logged out"
		redirect_to root_path
	end
end

app/controllers/users_controller.rb
     # register GET    /register(.:format)                users#new
     #    users POST   /users(.:format)                   users#create
     #     user GET    /users/:id(.:format)               users#show

class UsersController < ApplicationController
	before_action :set_user, only: [:show, :edit, :update]
	before_action :require_same_user, only: [:edit, :update]
	def index
	end

	def show
		@post = Post.where(user_id: @user.id)
		@comments = Comment.where(user_id: @user.id)
	end


	def new
		@user = User.new
	end

	def create
		@user = User.new(user_params)
		
		if @user.save
			flash[:notice] = "User has been successfully created"
			session[:user_id] = @user.id
			redirect_to root_path
		else
			render :new
		end
	end

	def edit
	end

	def update
		
		if @user.update(user_params)
			flash[:notice] = "User has been successfully Updated"
			redirect_to root_path
		else
			render :edit
		end
	end

	private 
	
	def user_params
		params.require(:user).permit(:username, :password)
	end

	def set_user
		@user = User.find(params[:id])
	end

	def require_same_user
		if current_user != @user 
			flash[:error] = "You don't have permission to do that"
			redirect_to root_path
		end
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
	def fix_url(str)
		str.starts_with?('http://') ? str : "http://#{str}"
	end 
	def fix_date(dt)
		dt.strftime("%d %b. %Y %I:%M%P %Z")
	end
end

app/views/categories/_category.html.erb
<span class="badge"><%= link_to category.name, category_path(category) %></span>

app/views/categories/index.html.erb
<%= render 'shared/content_title', title: "All Categories" %>

<% @categories.each do |category| %>
	<p><%= category.name %></p>
<%end%>

<%= link_to 'Add Cateogry', new_category_path, class: 'btn btn-success' %>

app/views/categories/new.html.erb
<%= render 'shared/content_title', title: "Create a New Category" %>

<div class="well row">
	<div class="form span4">
		<%= form_for @categories do |f| %>
			<%= f.label :name, "Category Name" %>
			<%= f.text_field :name %>
			<br/>
			<%= f.submit class: "btn btn-success" %>
		<%end %>
	</div>
		<%= render 'shared/error', obj: @categories %>
</div>

app/views/categories/show.html.erb
<% header = link_to("All Posts", posts_path)+" &raquo; #{@categories.name}".html_safe%>

<%= render 'shared/content_title', title: header %>

<% @categories.posts.each do |post| %>
	<%= render 'posts/post', post: post %>
<% end %>

app/views/comments/_comments.html.erb
<% show_post ||= false %>
<div class="row">
<% if logged_in? %>
 	<div class="span0 text-center well	">
		<%= link_to vote_post_comment_path(comment.post, comment, vote: true), method: 'post' do %>
			<i class="icon-arrow-up"></i>
		<%end%>
		<br/>
		<%=  comment.vote_total %>
		<br/>
		<%= link_to vote_post_comment_path(comment.post, comment, vote: false), method: 'post' do %>
			<i class="icon-arrow-down"></i>
		<%end%>
	</div>
<%elsif %>
  <div class="span0 text-center well  ">
      <%= comment.vote_total %>
      <%= "votes" %>
    </div>
<%end%>
 	<div class="well span9">
 		<em><%= comment.body %> </em>
 		<% if show_post %>
 			on <%= link_to comment.post.title, post_path(comment.post) %>
 		<% end %>
 		<br/>
 		<span class="quiet">by </span><%=link_to comment.user.username, user_path(comment.user) %>
		<small><%= fix_date(comment.created_at) %></small>
 	</div>
</div>
	

app/views/layouts/_messages.html.erb
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div class="alert alert-<%= name == "notice" ? "success" : "error" %>">
      <a class="close" data-dismiss="alert">&#215;</a>
      <%= content_tag :div, msg, :id => "flash_#{name}" %>
    </div>
  <% end %>
<% end %>

app/views/layouts/_navigation.html.erb
<ul class="nav">
  <li>
    <%= link_to "Postit!", root_path, :class => 'brand' %>
  </li>
</ul>
<% if logged_in? %>
<div class="nav_item">
	<%= link_to(new_post_path) do %>
		<button class="btn btn-success">
			<i class="icon-plus icon-white"></i>
				New Post
		</button>
	<%end %>
</div>
<%end %>

<div class="btn-group nav_item">
	<%= link_to "#", class: 'btn dropdown-toggle', 'data-toggle' => 'dropdown' do %>
		Categories <span class="caret"></span>
	<% end %>
	<ul class="dropdown-menu">
		<% Category.all.each do |category| %>
			<li><%= link_to category.name, category_path(category)  %></li>
		<%end%>
		<%if logged_in? %>
		<li class="divider"></li>
		<li>
			<%=link_to(new_category_path) do %>
				<i class="icon-plus"></i>
				New Category
			<%end %>
		</li>
		<%end%>
	</ul>
</div>
<!-- Will appear if you are logged in -->
<% if logged_in? %>
	<div class="btn-group nav_item ">
		<%= link_to "#", class: 'btn dropdown-toggle', 'data-toggle' => 'dropdown' do %>
			<i class="icon-user"></i>
			<%= current_user.username %>
			<span class="caret"></span>
			<% end %>
			<ul class="dropdown-menu">
				<li><%= link_to(user_path(session[:user_id])) do %>
					<i class="icon-user"></i>
					My Account
					<%end %>
				</li>
				<li><%= link_to(edit_user_path(session[:user_id])) do %>
					<i class="icon-pencil"></i>
					Edit User
					<%end %>
				</li>
				<li><%= link_to(logout_path) do %>
					<i class="icon-circle-arrow-right"></i>
					Logout
					<%end%>
				</li>
			</ul>
	</div>


<!-- Will appear if you are not logged in -->	
<% else %>
	<div class="nav_item ">
		<%= link_to(login_path) do %>
			<button class="btn btn-primary">
				<i class="icon-user icon-white"></i>
					Login
			</button>
		<%end %>
	</div>


	<div class="nav_item ">
		<%= link_to(register_path) do %>
			<button class="btn btn-default">
				<i class="icon-user "></i>
					Register
			</button>
		<%end %>
	</div>
<%end %>

app/views/layouts/application.html.erb
<!doctype html>
<html>
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Postit</title>
    <meta name="description" content="">
    <meta name="author" content="">
    <%= stylesheet_link_tag "application", :media => "all" %>
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tags %>
    <%= yield(:head) %>
  </head>
  <body>
    <header>
      <div class="navbar">
        <div class="navbar-inner">
          <div class="container">
            <%= render 'layouts/navigation' %>
          </div>
        </div>
      </div>
    </header>
    <div id="main" role="main">
      <div class="container">
         <div class="row">
          <div class="span12">
            <%= render 'layouts/messages' %>
            <%= yield %>
          </div>
        </div>
        <footer>
        </footer>
      </div> <!--! end of .container -->
    </div> <!--! end of #main -->
  </body>
</html>

app/views/posts/_form.html.erb
	<div class="well row">
		<div class="form span8">
			<%= form_for @post do |f| %>

				<%= f.label :title %>
				<%= f.text_field :title %>

				<%= f.label :url %>
				<%= f.text_field :url %>

				<%= f.label :description %>
				<%= f.text_area :description, rows: 5 %>

				<br/>
					<%= f.collection_check_boxes(:category_ids, Category.all, :id, :name) do |cb|%>
						<% cb.label(class: "checkbox inline") {cb.check_box(class: "checkbox") + cb.text} %>
					<% end %>
				<br/>
				<%= f.submit  class: "btn btn-default" %>
			<% end %>
		</div>
			<%= render 'shared/error', obj: @post %>
	</div>
		


</div>

app/views/posts/_post.html.erb
<div class="row">
	<% if logged_in? %>
		<div class="span0 text-center">
			<%= link_to vote_post_path(post, vote: true),method: 'post' do %>
				<i class="icon-arrow-up"></i>
			<%end%>
				<br/>
					<%= "#{post.vote_total}" %>
					<%= "votes" %>
				<br/>
				<%= link_to vote_post_path(post, vote: false),method: 'post' do %>
					<i class="icon-arrow-down"></i>
				<%end%>
		</div>
	<% else %>
		<div class="span0 text-center">
			<%= post.vote_total %>
			<%= "votes" %>
		</div>
	<%end%>
	<div class="span8 ">
		<p ><%= link_to post.title, fix_url(post.url) %> 
			<%= render post.categories %>
			<% if logged_in? %>
			<%= link_to 'Edit', edit_post_path(post), class: "pull-right" %>
			<% end %>
		<p> <%= post.description %>
		<p>
			<span class="quiet">posted by </span><%= link_to post.user.username, user_path(post.user.id) %>
			<small><%= fix_date(post.created_at) %></small>
		</p>
		<small>
			<%= link_to("#{post.comments.size} comments", post_path(post)) %>
		</small>
		<hr/>
	</div>
</div>

app/views/posts/edit.html.erb
<%= render 'shared/content_title', title: "Edit this Post" %>

<%= render 'form'%>

app/views/posts/index.html.erb
<%= render 'shared/content_title', title: "All Posts" %>

<% @post.each do |post| %>
	<%= render 'post', post: post%>
<%end%>

app/views/posts/new.html.erb
<%= render 'shared/content_title', title: "Create a New Post" %>

<%=render 'form' %>
	

app/views/posts/show.html.erb
<p class="pull-right">
<%=link_to 'edit this post', edit_post_path(@post)%>
</p>
<%= render 'shared/content_title', title: @post.title %>
<p><%= @post.title%></p>
<p><%= @post.description %></p>
<p><%= link_to @post.url, ''%></p>

<% if logged_in? %>
 <%= form_for [@post, @comments] do |f| %>
  <%= render 'shared/error', obj: @comments %>
 	<br/>
 	<div class="control-group">
 	<%= f.label :body, "Leave a Comment" %>
 	<%= f.text_area :body, row: 3, class: 'span4' %>
 	<br/>
 	</div>
 	<%= f.submit class: "btn btn-primary" %>
 <% end %>
<% end %>
 <%= render 'shared/content_title', title: "Comments:" %>

 <% @post.comments.each do |comment| %>
 	<%= render 'comments/comments', comment: comment %>
 <% end %>

app/views/posts/update.html.erb
<%= render 'shared/content_title', title: "Edit this Post" %>

<%= render 'form'%>

app/views/shared/_content_title.html.erb
<p class="lead">
	<%= title %>
	<hr/>

</p>

app/views/shared/_error.html.erb
<div class="error span4">
	<% if obj.errors.any? %>
		<div class='alert alert-error span4'>
			<h5>Please fix the following errors:</h5>
				<ul>
					<% obj.errors.full_messages.each do |msg| %>
						<li><%= msg %></li>
					<%end%>
				</ul>
		</div>
	<% end %>
</div>

app/views/shared/_post_form.html.erb
	<div class="well row">
		<div class="form span4">
			<%= form_for @post do |f| %>

				<%= f.label :title %>
				<%= f.text_field :title %>

				<%= f.label :url %>
				<%= f.text_field :url %>

				<%= f.label :description %>
				<%= f.text_area :description, rows: 5 %>
				<br/>
				<%= f.submit  class: "btn btn-default" %>
			<% end %>
		</div>
		<div class="error span4">
			<% if @post.errors.any? %>
			<div class='alert alert-error span4'>
				<h5>Please fix the following errors:</h5>
					<ul>
						<% @post.errors.full_messages.each do |msg| %>
						<li><%= msg %></li>
						<%end%>
					</ul>
			</div>
	<% end %>
		</div>
	</div>
</div>

app/views/users/_form.html.erb
<div class="well">
	<%= form_for @user do |f|%>
		<%= render 'shared/error', obj: @user %>
		<div class='control-group'>
			<br/>
			<%= f.label :username %>
			<%= f.text_field :username %>
		</div>
		<div class='control-group'>	
			<%= f.label :password %>
			<%= f.password_field :password %>
			<%= f.label :password_confirmation %>
			<%= f.password_field :password_confirmation %>
		</div>
		<br/>
		
		<%= f.submit class: "btn btn-primary"%>
	<% end %>
</div>

app/views/users/edit.html.erb
<%= render 'shared/content_title', title: "Edit Your Profile" %>

<%= render 'form' %>

app/views/users/new.html.erb
<%= render 'shared/content_title', title: "New User" %>
<%= render 'form' %>

app/views/users/show.html.erb
<%= render 'shared/content_title', title: "#{@user.username}'s account " %>

<div class="well">
	<dl class="dl-horizontal">
		<dt>Username:</dt>
		<dd><%= @user.username %></dd>
		<dt>Account Created At:</dt>
		<dd><%= fix_date(@user.created_at) %></dd>
		<dt>Number of Posts:</dt>
		<dd><%= @post.count %></dd>
		<dt>Number of Comments:</dt>
		<dd><%= @comments.count %></dd>
	</dl>
</div>

<%= render 'shared/content_title', title: "#{@user.username}'s activity" %>

<ul class="nav nav-tabs">
	<li class='<%= 'active' if params[:tab].nil? || params[:tab] == 'posts' %>'>
		<%= link_to "Posts (#{@post.count})", user_path(@user, tab: 'posts')%>
	</li>
	<li class='<%='active' if params[:tab] == 'comments' %>'>
		<%= link_to "Comments (#{@comments.count})", user_path(@user, tab: 'comments')%>
	</li>
</ul>

<% if params[:tab].nil? || params[:tab] == 'posts' %>
	<% @post.each do |post| %>
		<%= render 'posts/post', post: post %>
	<%end%>
<% elsif params[:tab] == 'comments' %>
	<% @comments.each do |comment| %>
		<%= render 'comments/comments', comment: comment, show_post: true %>
	<% end %>
<% end %>